//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTxtCsv {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTxtCsv {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTxtCsv() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.ResTxtCsv", typeof(ResTxtCsv).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,name,description,iconName,color,isDefault,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Food,Expenses related to food,food,#FF5733,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Transport,Transportation expenses,transport,#45B39D,false,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Entertainment,Entertainment expenses,entertainment,#9B59B6,false,2
        ///.
        /// </summary>
        internal static string category_csv {
            get {
                return ResourceManager.GetString("category_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,name,description,iconName,color,isDefault,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Food,Expenses related to food,food,#FF5733,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Transport,Transportation expenses,transport,#45B39D,false,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Entertainment,Entertainment expenses,entertainment,#9B59B6,false,2
        ///.
        /// </summary>
        internal static string category_txt {
            get {
                return ResourceManager.GetString("category_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,name,description,iconName,color,isDefault,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Food,Expenses related to food,food,#FF5733,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Transport,Transportation expenses,transport,#45B39D,false,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Entertainment,Entertainment expenses,entertainment,#9B59B6,false,2
        ///.
        /// </summary>
        internal static string expense_csv {
            get {
                return ResourceManager.GetString("expense_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,name,description,iconName,color,isDefault,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Food,Expenses related to food,food,#FF5733,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Transport,Transportation expenses,transport,#45B39D,false,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,Entertainment,Entertainment expenses,entertainment,#9B59B6,false,2
        ///.
        /// </summary>
        internal static string expense_txt {
            get {
                return ResourceManager.GetString("expense_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,amount,currency,categoryId,description,isExpense,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,50,USD,1,Lunch at a restaurant,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,30,USD,1,Groceries,true,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,20,EUR,2,Taxi ride,true,1
        ///4,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,15,USD,3,Movie tickets,true,2
        ///5,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,10,EUR,3,Concert tickets,true,2
        ///6,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,40,USD,4,Cl [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string user_csv {
            get {
                return ResourceManager.GetString("user_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id,createdAt,updatedAt,amount,currency,categoryId,description,isExpense,userId
        ///1,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,50,USD,1,Lunch at a restaurant,true,1
        ///2,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,30,USD,1,Groceries,true,1
        ///3,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,20,EUR,2,Taxi ride,true,1
        ///4,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,15,USD,3,Movie tickets,true,2
        ///5,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,10,EUR,3,Concert tickets,true,2
        ///6,2024-04-28T12:00:00Z,2024-04-28T12:00:00Z,40,USD,4,Cl [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string user_txt {
            get {
                return ResourceManager.GetString("user_txt", resourceCulture);
            }
        }
    }
}
